interface Error {
  [key: string]: string;
}

const errors : Error = {
  no_internet_connection: "No hay conexión a internet",
  session_error: "Error en la sesión",
  active_required: "Se requiere estado activo o inactivo",
  actual_required: "Se requiere estado real o no real",
  ages_duplicated: "No se pueden proporcionar edades duplicadas",
  ages_products_mismatch: "Las edades y los productos no coinciden",
  ages_required: "Se requiere al menos una edad",
  area_required: "Se requiere un área",
  brand_not_found: "La marca no existe",
  checked_invalid: "El estado de verificación no es válido",
  checklist_not_allowed: "La lista de verificación no está permitida",
  code_expired: "El código ha expirado",
  code_expiry_required: "Se requiere la fecha de expiración del código",
  dates_invalid: "Las fechas no son válidas",
  deliverable_not_found: "El entregable no existe",
  distribution_required: "Se requiere una distribución",
  email_exists: "El correo electrónico ya existe",
  email_required: "Se requiere un correo electrónico",
  end_date_required: "Se requiere una fecha de finalización",
  entry_not_found: "La entrada no existe",
  entries_not_found: "Una o más entradas no existen",
  invalid_credentials: "Credenciales inválidas",
  invalid_form_data: "Datos del formulario inválidos",
  invalid_token: "El token no es válido",
  missing_fields: "Faltan campos obligatorios",
  number_invalid: "El número no es válido",
  order_by_column_invalid: "La columna de ordenación no es válida",
  order_by_direction_invalid: "La dirección de ordenación no es válida",
  otp_invalid: "El código de seguridad no es válido",
  otp_error: "Error al generar el código de seguridad",
  project_creator_not_found: "El creador no existe para el proyecto",
  project_not_found: "El proyecto no existe",
  status_not_found: "El estado no existe",
  too_many_meeting_dates: "Se pueden proporcionar hasta 3 fechas de reunión",
  unauthorized: "Usuario no autorizado",
  unexpected_error: "Ha ocurrido un error inesperado",
  user_email_required: "Se requiere el correo electrónico del usuario",
  user_id_required: "Se requiere el ID del usuario",
  user_not_found: "El usuario no existe",
  brand_already_exists: "La marca ya existe",
  creator_not_found: "El creador no existe",
  creator_types_required: "Se requieren habilidades del creador",
  name_required: "Se requiere un nombre",
  notification_not_found: "La notificación no existe",
  otp_already_enabled: "El código de seguridad ya está habilitado",
  phone_required: "Se requiere un número de teléfono",
  not_course_owner: "No eres el propietario del curso",
  student_not_enrolled: "El estudiante no está inscrito en el curso",
  llm_error: "Error al comunicarse con el modelo de lenguaje",
};

export function getErrorMessage(errorKey: string): string {
  return errors[errorKey] || "Ha ocurrido un error inesperado";
}
